networks:
  caddy:
    external: true


services:
  app:
    container_name: bff_app
    networks:
      - caddy
    dns:
      - 1.1.1.1
      - 8.8.8.8
  cache:
    command: >
      redis-server 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 256M
