services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      ENV: prod
      APP_PORT: 3000
      CACHE_DSN: cache:6379
    env_file:
      - .env

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
